# Generated by Django 3.0.5 on 2020-05-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_studentextra_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='teacherextra',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
